apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: webapp-color
  labels:
    app: webapp
spec:
  containers:
  - name: simple-webapp
    image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      value: "red"
    ports:
    - containerPort: 8080