apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: pod-blue
  namespace: production
  labels:
    app: web
spec:
  containers:
    - name: webapp
      image: mmumshad/simple-webapp-color
      env:
        - name: APP_COLOR
          value: "blue"